platform :android do
  desc 'Build the Android application.'
  lane :build do
    # gradle(task: 'clean', project_dir: 'android/')
    # increment_version_name(app_project_dir: '**/app', bump_type: 'minor')
    increment_version_name(app_project_dir: 'android/app', bump_type: 'minor')
    # patch for bug fixes
    # minor small features 
    # major braking changes
    # increment_version_code(app_project_dir: '**/app')
    increment_version_code(app_project_dir: 'android/app')
    gradle(
      task: 'bundle',
      build_type: 'release',
      project_dir: 'android/',
      properties: {
          "MYAPP_RELEASE_STORE_FILE" => ENV["ANDROID_KEYSTORE_PATH"],
          "MYAPP_RELEASE_STORE_PASSWORD" => ENV["ANDROID_KEYSTORE_PASSWORD"],
          "MYAPP_RELEASE_KEY_ALIAS" => ENV["ANDROID_KEY_ALIAS"],
          "MYAPP_RELEASE_KEY_PASSWORD" => ENV["ANDROID_KEY_PASSWORD"]
        }
    )
  end
end