name: Manual Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Stay on LTS for better stability with Expo
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.2"
          bundler-cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Decode Keystore
        run: |
          # This creates the directory path so the echo command doesn't fail
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-app-release.jks

      - name: Run Fastlane Build
        run: bundle exec fastlane android build
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/android/app/my-app-release.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Bundle (AAB)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 5
